// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: archivo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- Mensajes para AssignService ---
type EmergencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Magnitude     int32                  `protobuf:"varint,4,opt,name=magnitude,proto3" json:"magnitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmergencyRequest) Reset() {
	*x = EmergencyRequest{}
	mi := &file_archivo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmergencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmergencyRequest) ProtoMessage() {}

func (x *EmergencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_archivo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmergencyRequest.ProtoReflect.Descriptor instead.
func (*EmergencyRequest) Descriptor() ([]byte, []int) {
	return file_archivo_proto_rawDescGZIP(), []int{0}
}

func (x *EmergencyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EmergencyRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *EmergencyRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *EmergencyRequest) GetMagnitude() int32 {
	if x != nil {
		return x.Magnitude
	}
	return 0
}

type DroneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DroneId       string                 `protobuf:"bytes,1,opt,name=drone_id,json=droneId,proto3" json:"drone_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DroneResponse) Reset() {
	*x = DroneResponse{}
	mi := &file_archivo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DroneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DroneResponse) ProtoMessage() {}

func (x *DroneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_archivo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DroneResponse.ProtoReflect.Descriptor instead.
func (*DroneResponse) Descriptor() ([]byte, []int) {
	return file_archivo_proto_rawDescGZIP(), []int{1}
}

func (x *DroneResponse) GetDroneId() string {
	if x != nil {
		return x.DroneId
	}
	return ""
}

func (x *DroneResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// --- Mensajes para DroneService ---
type DroneEmergencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Magnitude     int32                  `protobuf:"varint,4,opt,name=magnitude,proto3" json:"magnitude,omitempty"`
	DroneId       string                 `protobuf:"bytes,5,opt,name=drone_id,json=droneId,proto3" json:"drone_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DroneEmergencyRequest) Reset() {
	*x = DroneEmergencyRequest{}
	mi := &file_archivo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DroneEmergencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DroneEmergencyRequest) ProtoMessage() {}

func (x *DroneEmergencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_archivo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DroneEmergencyRequest.ProtoReflect.Descriptor instead.
func (*DroneEmergencyRequest) Descriptor() ([]byte, []int) {
	return file_archivo_proto_rawDescGZIP(), []int{2}
}

func (x *DroneEmergencyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DroneEmergencyRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *DroneEmergencyRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *DroneEmergencyRequest) GetMagnitude() int32 {
	if x != nil {
		return x.Magnitude
	}
	return 0
}

func (x *DroneEmergencyRequest) GetDroneId() string {
	if x != nil {
		return x.DroneId
	}
	return ""
}

type DroneEmergencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DroneEmergencyResponse) Reset() {
	*x = DroneEmergencyResponse{}
	mi := &file_archivo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DroneEmergencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DroneEmergencyResponse) ProtoMessage() {}

func (x *DroneEmergencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_archivo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DroneEmergencyResponse.ProtoReflect.Descriptor instead.
func (*DroneEmergencyResponse) Descriptor() ([]byte, []int) {
	return file_archivo_proto_rawDescGZIP(), []int{3}
}

func (x *DroneEmergencyResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// --- Mensajes para MonitoringService ---
type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_archivo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_archivo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_archivo_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_archivo_proto protoreflect.FileDescriptor

const file_archivo_proto_rawDesc = "" +
	"\n" +
	"\rarchivo.proto\x12\vdronesystem\x1a\x1bgoogle/protobuf/empty.proto\"~\n" +
	"\x10EmergencyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1c\n" +
	"\tmagnitude\x18\x04 \x01(\x05R\tmagnitude\"B\n" +
	"\rDroneResponse\x12\x19\n" +
	"\bdrone_id\x18\x01 \x01(\tR\adroneId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x9e\x01\n" +
	"\x15DroneEmergencyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1c\n" +
	"\tmagnitude\x18\x04 \x01(\x05R\tmagnitude\x12\x19\n" +
	"\bdrone_id\x18\x05 \x01(\tR\adroneId\"0\n" +
	"\x16DroneEmergencyResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"*\n" +
	"\x0eUpdateResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2U\n" +
	"\rAssignService\x12D\n" +
	"\vAssignDrone\x12\x1d.dronesystem.EmergencyRequest\x1a\x16.google.protobuf.Empty2l\n" +
	"\fDroneService\x12\\\n" +
	"\x11AtenderEmergencia\x12\".dronesystem.DroneEmergencyRequest\x1a#.dronesystem.DroneEmergencyResponse2[\n" +
	"\x11MonitoringService\x12F\n" +
	"\rStreamUpdates\x12\x16.google.protobuf.Empty\x1a\x1b.dronesystem.UpdateResponse0\x01B\n" +
	"Z\b./;protob\x06proto3"

var (
	file_archivo_proto_rawDescOnce sync.Once
	file_archivo_proto_rawDescData []byte
)

func file_archivo_proto_rawDescGZIP() []byte {
	file_archivo_proto_rawDescOnce.Do(func() {
		file_archivo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_archivo_proto_rawDesc), len(file_archivo_proto_rawDesc)))
	})
	return file_archivo_proto_rawDescData
}

var file_archivo_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_archivo_proto_goTypes = []any{
	(*EmergencyRequest)(nil),       // 0: dronesystem.EmergencyRequest
	(*DroneResponse)(nil),          // 1: dronesystem.DroneResponse
	(*DroneEmergencyRequest)(nil),  // 2: dronesystem.DroneEmergencyRequest
	(*DroneEmergencyResponse)(nil), // 3: dronesystem.DroneEmergencyResponse
	(*UpdateResponse)(nil),         // 4: dronesystem.UpdateResponse
	(*emptypb.Empty)(nil),          // 5: google.protobuf.Empty
}
var file_archivo_proto_depIdxs = []int32{
	0, // 0: dronesystem.AssignService.AssignDrone:input_type -> dronesystem.EmergencyRequest
	2, // 1: dronesystem.DroneService.AtenderEmergencia:input_type -> dronesystem.DroneEmergencyRequest
	5, // 2: dronesystem.MonitoringService.StreamUpdates:input_type -> google.protobuf.Empty
	5, // 3: dronesystem.AssignService.AssignDrone:output_type -> google.protobuf.Empty
	3, // 4: dronesystem.DroneService.AtenderEmergencia:output_type -> dronesystem.DroneEmergencyResponse
	4, // 5: dronesystem.MonitoringService.StreamUpdates:output_type -> dronesystem.UpdateResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_archivo_proto_init() }
func file_archivo_proto_init() {
	if File_archivo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_archivo_proto_rawDesc), len(file_archivo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_archivo_proto_goTypes,
		DependencyIndexes: file_archivo_proto_depIdxs,
		MessageInfos:      file_archivo_proto_msgTypes,
	}.Build()
	File_archivo_proto = out.File
	file_archivo_proto_goTypes = nil
	file_archivo_proto_depIdxs = nil
}
